name: lint

on:
  push:
    branches: ['*']
    paths-ignore:
      - 'os-image/**'
      - 'scripts/**'
  pull_request:
    paths-ignore:
      - 'os-image/**'
      - 'scripts/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cocoon-macos
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.2

      - name: Check formatting
        run: golangci-lint fmt --diff
